name: disk_space_plus
description: A tiny Flutter Plugin to show free and total disk space.
version: 0.2.3
repository: https://github.com/harrowmykel/disk_space_plus

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.piccmaq.disk_space_plus
        pluginClass: DiskSpacePlusPlugin
      ios:
        pluginClass: SwiftDiskSpacePlusPlugin
